# Generated by Django 5.1.7 on 2025-03-27 02:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2025, 3, 27))),
                ('reason', models.CharField()),
                ('completed', models.BooleanField(default=False)),
                ('place_of_service', models.CharField()),
                ('notes', models.TextField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='car_app.car')),
            ],
        ),
    ]
