# Generated by Django 5.1.7 on 2025-03-27 02:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 3, 27, 2, 53, 38, 638176, tzinfo=datetime.timezone.utc)),
        ),
    ]
