# Generated by Django 5.1.7 on 2025-03-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_width', models.IntegerField()),
                ('aspect_ratio', models.IntegerField()),
                ('rim_size', models.IntegerField()),
            ],
        ),
    ]
