# Generated by Django 5.1.7 on 2025-03-28 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird_app', '0001_initial'),
        ('owner_app', '0002_remove_owner_number_of_pets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birds', to='owner_app.owner'),
        ),
    ]
