# Generated by Django 5.1.7 on 2025-03-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_alter_student_personal_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='personal_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
