# Generated by Django 5.1.7 on 2025-03-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0010_alter_subject_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='students',
        ),
        migrations.AddField(
            model_name='subject',
            name='student',
            field=models.ManyToManyField(related_name='subjects', to='student_app.student'),
        ),
    ]
