# Generated by Django 5.1.7 on 2025-03-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0011_rename_subject_name_subject_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.ManyToManyField(related_name='students', to='student_app.subject'),
        ),
    ]
