# Generated by Django 5.1.7 on 2025-03-26 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0012_remove_subject_student_student_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='subject',
            new_name='subjects',
        ),
    ]
