# Generated by Django 5.1.7 on 2025-03-26 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engine_app', '0001_initial'),
        ('owner_app', '0001_initial'),
        ('tire_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField()),
                ('model', models.CharField()),
                ('year', models.CharField()),
                ('mileage', models.BigIntegerField(default=0)),
                ('engine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='engine_app.engine')),
                ('owners', models.ManyToManyField(related_name='cars', to='owner_app.owner')),
                ('tire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='tire_app.tire')),
            ],
        ),
    ]
